// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq_cSejAMWB075JnsGc0pYGWtaEUX69p8',
    appId: '1:815991626377:web:705f558045aead12bd8458',
    messagingSenderId: '815991626377',
    projectId: 'awesome-project-wow',
    authDomain: 'awesome-project-wow.firebaseapp.com',
    storageBucket: 'awesome-project-wow.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS4sDr-NwF79r22zd7QNnZWoo8-MS0MsU',
    appId: '1:815991626377:android:a921ccc68abe9246bd8458',
    messagingSenderId: '815991626377',
    projectId: 'awesome-project-wow',
    storageBucket: 'awesome-project-wow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB45XMRPcSCA07ywUKaASe0LGvoqhra12k',
    appId: '1:815991626377:ios:d2b09811562a819fbd8458',
    messagingSenderId: '815991626377',
    projectId: 'awesome-project-wow',
    storageBucket: 'awesome-project-wow.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB45XMRPcSCA07ywUKaASe0LGvoqhra12k',
    appId: '1:815991626377:ios:d2b09811562a819fbd8458',
    messagingSenderId: '815991626377',
    projectId: 'awesome-project-wow',
    storageBucket: 'awesome-project-wow.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq_cSejAMWB075JnsGc0pYGWtaEUX69p8',
    appId: '1:815991626377:web:3b26b7839630920fbd8458',
    messagingSenderId: '815991626377',
    projectId: 'awesome-project-wow',
    authDomain: 'awesome-project-wow.firebaseapp.com',
    storageBucket: 'awesome-project-wow.appspot.com',
  );
}
